name: Cloud Application Solution

on:
  workflow_dispatch:

env:
  SYSTEM_ACCESSTOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  actions: write

jobs:
  DetermineChanges:
    name: Identify Modified Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect Changes and Write Files to Output File
        run: |
          git diff --name-only HEAD~1 HEAD | grep -E '\.bicep$' | xargs -n1 basename | sed 's/\.bicep$//' > output.txt
          cat output.txt
          while IFS= read -r entry; do
            echo "Detected changes in file: $entry"
          done < output.txt

      - name: Upload Detected Changes Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DetectedChanges
          path: output.txt

  HandleModifiedFiles:
    name: Handle Modified Files
    needs: DetermineChanges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Detected Changes Artifact
        uses: actions/download-artifact@v4
        with:
          name: DetectedChanges
          path: ./artifacts

      - name: Trigger another GitHub Actions workflow
        run: |
          while IFS= read -r fileName; do
            if [ -n "$fileName" ]; then
              echo "Triggering workflow for file: $fileName"
              curl -X POST \
              -H "Accept: application/vnd.github+json" \
              echo "1" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              echo "2" \
              https://api.github.com/repos/${{ github.repository }}/dispatches \
              echo "3" \
              -d "{
                \"event_type\": \"bicep-file-change\",
                \"client_payload\": {
                  \"fileName\": \"$fileName\"
                }
              }"
            fi
          done < ./artifacts/output.txt