name: Build Bicep Files

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  # Optional: Allow manual runs with custom inputs
  workflow_dispatch:
    inputs:
 #     fundamentalsPath:
#        description: 'Path to the fundamentals Bicep file'
#        required: true
#        default: ''
      mainPath:
        description: 'Path to the main Bicep file'
        required: true
        default: ''
      acrConnection:
        description: 'Azure subscription connection name'
        required: true
        default: 'STACKMEISTEREI'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Azure using Service Principal credentials from GitHub Secrets
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Build the Bicep files using Azure CLI
      - name: Authenticate to ACR and Build Bicep Files
        run: |
          
          az bicep build --file "${{ github.event.inputs.mainPath || '' }}"
        shell: bash

     # az bicep build --file "${{ github.event.inputs.fundamentalsPath || '' }} this needs to be inside run in the future"   