name: Build Bicep Files
# NEEDS ROLE ASSIGNMENT ACRPULL 
# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  # workflow_dispatch allows manual runs with custom inputs
  workflow_dispatch:
    inputs:
 #     fundamentalsPath:
#        description: 'Path to the fundamentals Bicep file'
#        required: true
#        default: ''
      mainPath:
        description: 'Path to the main Bicep file'
        required: true
        default: 'CPS/main.bicep'
      acrConnection:
        description: 'Azure subscription connection name'
        required: true
        default: 'STACKMEISTEREI'
permissions:
  id-token: write
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      # This Login uses OIDC to connect to azure using the secrets I stored in GitHub
      - name: Azure Login
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
           # "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}"
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            enable-AzPSSession: true
            
      - name: Debug Inputs
        run: |
         echo "mainPath: ${{ github.event.inputs.mainPath }}"
      
      
      
      
      - name: Authenticate to ACR and Build Bicep Files
        run: |
          
          az bicep build --file ${{ github.event.inputs.mainPath }}
        shell: bash

     # az bicep build --file "${{ github.event.inputs.fundamentalsPath || '' }} this needs to be inside run in the future"   
