name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      fileName:
        description: 'File name'
        required: true
        default: ''
      mainPath:
        description: 'Main path'
        required: true
        default: '${{ github.workspace }}/Placeholder/CAS/'

env:
  azureConnection: 'Placeholder'
  location: 'Placeholder'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Preflight Validation
        id: preflight
        run: |
          TEMPLATE_PATH="${{ github.event.inputs.mainPath }}/${{ github.event.inputs.fileName }}.bicep"
          PARAMETERS_PATH="${{ github.event.inputs.mainPath }}/${{ github.event.inputs.fileName }}.bicepparam"
          az deployment tenant validate \
          --location ${{ env.location }} \
          --name "${{ github.run_number }}-CAS-${{ github.event.inputs.fileName }}" \
          --template-file "$TEMPLATE_PATH" \
          --parameters "$PARAMETERS_PATH"
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Perform What-If Analysis
        id: whatif
        run: |
          TEMPLATE_PATH="${{ github.event.inputs.mainPath }}/${{ github.event.inputs.fileName }}.bicep"
          PARAMETERS_PATH="${{ github.event.inputs.mainPath }}/${{ github.event.inputs.fileName }}.bicepparam"
          az deployment tenant what-if \
          --location ${{ env.location }} \
          --name "${{ github.run_number }}-CAS-${{ github.event.inputs.fileName }}" \
          --template-file "$TEMPLATE_PATH" \
          --parameters "$PARAMETERS_PATH"
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Manual Approval
        uses: hmarr/auto-approve-action@v2
        with:
          timeout-minutes: 60
          instructions: 'Please approve the CAS Main deployment'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy CAS
        id: deploy
        run: |
          TEMPLATE_PATH="${{ github.event.inputs.mainPath }}/${{ github.event.inputs.fileName }}.bicep"
          PARAMETERS_PATH="${{ github.event.inputs.mainPath }}/${{ github.event.inputs.fileName }}.bicepparam"
          az deployment tenant create \
          --location ${{ env.location }} \
          --name "${{ github.run_number }}-CAS-${{ github.event.inputs.fileName }}" \
          --template-file "$TEMPLATE_PATH" \
          --parameters "$PARAMETERS_PATH"
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
