name: Test Action

    
on:
  repository_dispatch:
    types: [registry_package]


jobs: 
    test-job:
        name: Test Job
        runs-on: ubuntu-latest
        if: 
        steps:
            - run: |
                echo "Testing the job"

    test-job2:
        name: Test Job 2
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Testing the job 2"
