name: Webhook Listener for Registry Package

on:
  repository_dispatch:
  registry_package:
    types: [published]


jobs:
    
  test_printdigest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch }}
      
      
      - name: Test container digest
        run: echo "Digest is ${{ github.event.client_payload.container_metadata.tag.digest }}"

  process_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Latest Tag
        run: echo "testfrom postman"
