name: Update Azure Container Apps

permissions:
  id-token: write
  contents: read  
on:
    repository_dispatch:
      types:
        - package_push_latest
        - package_push_rc
        - package_push_prod

    # registry_package:
    #   types: [published]
    workflow_dispatch:  # Allows manual triggering

jobs:
  update-container-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true



      - name: Update Container Apps latest
        if: ${{ github.event.action == 'package_push_latest' }}
        run: |
           echo "Updating container apps with the latest image"
           echo "Tag: ${{ github.event.client_payload.tag }}"
           echo "Image: ${{ github.event.client_payload.image }}"



      - name: Update Container Apps rc
        if: ${{ github.event.action == 'package_push_rc' }}
        run: |
           echo "Updating container apps with the dev image"
           echo "sha: ${{ github.event.client_payload.sha }}"
        
        

      - name: Update Container Apps prod
        if: ${{ github.event.action == 'package_push_prod' }}
        run: |
           echo "Updating container apps with the prod image"
           







   #   - name: Login to GHCR
    #    run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u eldensokoli --password-stdin
           
     # - name: Pull Docker image
      #  run: docker pull ghcr.io/eldensokoli/test-project:latest


      # - name: Update Container Apps
        # run: |
        #     IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/eldensokoli/test-project:latest | cut -d'@' -f2)

        #     for app in test-container-app1 test-container-app2 test-container-app3; do
        #       echo "Updating container app: $app with image sha: $IMAGE_SHA"
        #       az containerapp update \
        #       --name "$app" \
        #       --resource-group containerapps-test \
        #       --image "ghcr.io/eldensokoli/test-project@$IMAGE_SHA" \
        #       --tags $IMAGE_SHA
        #       done
      
      


  

        #- name: Update Container Apps
        # run: |
        #     for app in container-app1 container-app2 container-app3; do
        #       az containerapp update \
        #         --name $app \
        #         --resource-group containerapps-test \
        #         --image ghcr.io/eldensokoli/test-project:latest
        #     done


















# name: Update Azure Container Apps

# on:
#     repository_dispatch:
#     registry_package:
#       types: [published]
#     workflow_dispatch:  # Allows manual triggering

# jobs:
#   update-container-apps:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Login to Azure via OIDC
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    
#       - name: Update Container Apps
#         run: |
#             for app in dab-ebanking-tst dab-gateway-tst dab-operations-tst; do
#               az containerapp update \
#                 --name $app \
#                 --resource-group celsion-tst-apps \
#                 --image ghcr.io/celsion-bank/digital-asset-backbone:latest
#             done
