name: Test Action

    
on: 
    push: 
        branches: 
            - main

    workflow_dispatch: 

        
jobs: 
    test-job:
        name: Test Job
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Testing the job"