name: Webhook Listener for Registry Package

on:
  repository_dispatch:
    types: [package_published] 

jobs:
  process_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Latest Tag
        run: echo "test"
