name: Update Azure Container Apps

on:
    repository_dispatch:
        types:
          - package_push_dev 

    # registry_package:
    #   types: [published]
    workflow_dispatch:  # Allows manual triggering

jobs:
  update-container-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update Container Apps in dev
        run: |
          echo "Updating container apps in dev environment"
        
        
        # run: |
        #     IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/eldensokoli/test-project:dev | cut -d'@' -f2)

        #     for app in test-container-app1 test-container-app2 test-container-app3; do
        #       echo "Updating container app: $app with image sha: $IMAGE_SHA"
        #       az containerapp update \
        #       --name "$app" \
        #       --resource-group containerapps-test \
        #       --image "ghcr.io/eldensokoli/test-project@$IMAGE_SHA" \
        #       --tags $IMAGE_SHA
        #       done
      