name: Test Action

    
on: 
    repository_dispatch: 
        types:
            - redeploy-containerapp
    workflow_dispatch:


jobs: 
    test-job:
        name: Test Job
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Testing the job"